- checkout/mint-leaf.yml
- greeting/mint-leaf.yml
- setup-go/mint-leaf.yml
- setup-node/mint-leaf.yml
- setup-ruby/mint-leaf.yml
I'll add a check to Cloud to prevent uploading a leaf with a name and a version that matches a published name+version. That way we'll get a failure on feature branch builds which neglect to bump the version number.
> Bump versions to fix publish on main

- .mint/ci.yml
- checkout/README.md
- checkout/mint-leaf.yml
- greeting/mint-leaf.yml
- per-leaf-tasks.template.yml
- setup-go/README.md
- setup-go/mint-leaf.yml
- setup-node/README.md
- setup-node/mint-leaf.yml
- setup-ruby/README.md
- setup-ruby/mint-leaf.yml
Most of the time, we should get a cache hit on the Mint task which builds the zip file for each leaf. However, if we do not get a cache hit, and we do not modify the leaf, we want to produce a zip file with the same digest as previously built so that we don't release a new version of unchanged leaves.
I adapted some code from this blog post:
https://zerostride.medium.com/building-deterministic-zip-files-with-built-in-commands-741275116a19
And if this doesn't work, we could use a deterministic zip utility such as:
https://github.com/timo-reymann/deterministic-zip
> Attempt to make zip files deterministic

- per-leaf-tasks.template.yml
- publish-tasks.template.yml
Right now we don't actually need these leaves in staging. If we do end up wanting them there, I think it'd be better for us to set up an out-of-band replication process from production → staging instead. Removing staging from this build will make it easier for this repository to serve as a pattern for other repositories for leaves and will make #19 more straightforward.
> Remove publishing leaves to staging

- git-clone/README.md
- git-clone/mint-leaf.yml
The `latest-sha-cache-buster` output is unaffected, but we always want to run the task that determines the latest sha based on the provided ref.
> Replace run ID-based CACHE_BUST with cache:false

- git-clone/README.md
- git-clone/mint-leaf.yml
Turns out that `git -c ... clone` is different than `git clone -c ...`. This updates our clone command so that it sets the credential helper config in the repository for future git commands to use.
> Fixes setting the credential helper when cloning

- aws/assume-role/README.md
- aws/assume-role/mint-ci-cd.template.yml
- aws/assume-role/mint-leaf.yml
Non-zero exits within a subshell do not bubble up. This change ensures failures within `assume-role-with-web-identity` fail the leaf.
Note: I could not leave the demonstrating test in as we have no way to continue on failures and then inspect the outcome of a leaf today.
> Ensure leaf fails when session name is too long

- mint/install-go/README.md
- mint/install-go/bin/install-go
- mint/install-go/mint-ci-cd.template.yml
- mint/install-go/mint-leaf.yml
- Download all versions from golang.org when fetching releases. Without "include=all", only the last two majors are fetched.
- Fix the test for the target go version. Previously we would match the regex `${target_version}.+`, but this would download `go1.20` if you really wanted 1.2.
> Fix install-go

- google-cloud/install-cli/README.md
- google-cloud/install-cli/mint-leaf.yml
Remove the original downloaded file and delete the installation "backup," which `gcloud` makes whenever you add/remove components. The resulting layer is less than half the size it was before. (Still not great, but closer to `aws/install-cli`.)
> Slim down default google-cloud/install-cli leaf output.

- hashicorp/install-terraform/mint-ci-cd.template.yml
Failed on `main` in this run:
https://cloud.rwx.com/mint/rwx/runs/48ed04c48fd547b086ce5fbc3d2cc58b
Presumably due to this isseu:
https://stackoverflow.com/questions/19120263/why-exit-code-141-with-grep-q
> Fix flake in terraform tests

- mint/install-cli/README.md
- mint/install-cli/mint-leaf.yml
Updates `mint/install-cli` to fetch the latest `v0` daily if specifying `v0` for the version
> Periodically bust the cache for mint/install-cli

- mint/git-clone/README.md
- mint/git-clone/mint-ci-cd.template.yml
- mint/git-clone/mint-leaf.yml
Rename the environment variable used within the git-clone leaf from `GITHUB_ACCESS_TOKEN` to `GITHUB_TOKEN` to align with the `gh` cli.
> [mint/git-clone] Rename internal variable to GITHUB_TOKEN.

- mint/update-leaves-github/README.md
- mint/update-leaves-github/mint-ci-cd.template.yml
- mint/update-leaves-github/mint-leaf.yml
`mint leaves update` [no longer requires RWX authentication](https://github.com/rwx-research/mint-cli/pull/68), so don't require an `rwx-access-token`. 🎉
> Remove rwx-access-token parameter from mint/update-leaves-github.

- mint/git-clone/README.md
- mint/git-clone/mint-ci-cd.template.yml
- mint/git-clone/mint-leaf.yml
This version of `mint/git-clone` exposes metadata to tasks which `use` this leaf. The change sets new environment variables which are configured to have no impact to subsequent tasks' cache keys by default. With no additional configuration, it's safe to use these as metadata for tools which request additional context of the environment they run in (e.g. code coverage, parallel test runners, etc.).
In the worst case (using `meta-ref`) this has 3 extra git commands. In other cases, it has 2 extra.
> Expose cache-excluded metadata to tasks which use `mint/git-clone`

- mint/git-clone/README.md
- mint/git-clone/mint-leaf.yml
I need a few more pieces of meta for one of the integrations we're going to update.
Additionally, this moves most of our `params` usage in `git-clone` to instead set an environment variable and use bash expansion on the environment variable. The goal being that this should better handle double quotes/spaces/etc
> Expose more meta in git-clone; prefer setting env when accessing params

- mint/git-clone/README.md
- mint/git-clone/mint-ci-cd.template.yml
- mint/git-clone/mint-leaf.yml
- mint/update-leaves-github/README.md
- mint/update-leaves-github/mint-ci-cd.template.yml
- mint/update-leaves-github/mint-leaf.yml
`git for-each-ref` only returns branches and tags under `refs/heads` and `refs/tags` that you have locally; all the remote-only branches are only available under the prefix `refs/remotes`. This updates the clone leaf to use `git ls-remote --heads --tags` instead.
Our test didn't catch this because it used the latest commit on main, but main _is_ checked out locally so it didn't reproduce the issue. I added another test for a non-main commit which does reproduce it.
>  Fixes determining the MINT_GIT_REF for commit SHAs that are not on main 

- mint/update-leaves-github/README.md
- mint/update-leaves-github/mint-ci-cd.template.yml
- mint/update-leaves-github/mint-leaf.yml
We believe using the branch name will be safer than using labels. The only PRs to be considered will still be constrained to those opened by the same private GitHub App.
> [mint/update-leaves-github] Use branch name to find open PRs.

- google-cloud/auth-oidc/README.md
- google-cloud/auth-oidc/mint-ci-cd.template.yml
- google-cloud/auth-oidc/mint-leaf.yml
Expose the underlying service token lifetime configuration offered by gcloud.
> [google-cloud/auth-oidc] Add service token lifetime parameter.

- mint/git-clone/README.md
- mint/git-clone/mint-leaf.yml
This is no longer needed now that we include `jq` in the base image
> Remove the jq task from git-clone

- mint/install-elixir/README.md
- mint/install-elixir/mint-ci-cd.template.yml
- mint/install-elixir/mint-leaf.yml
After merging leaf will be available at:
https://cloud.rwx.com/leaves/mint/install-elixir
Example of error if the `mint/install-elixir` task is not configured to `use` and erlang install:
https://cloud.rwx.com/mint/rwx/runs/face251f0668482e837646d9a5d08c8b
> Add a leaf to install elixir

- google/install-chrome/README.md
- google/install-chrome/mint-ci-cd.template.yml
- google/install-chrome/mint-leaf.yml
This missing test was an oversight on my part during the initial implementation and it uncovers a bug with the bash regular expressions (seems like `\d` isn't available!)
> Ensure full version numbers work when installing chrome

- .mint/build-tasks.mjs
- cspell.yaml
- google/install-chrome/README.md
- google/install-chrome/mint-ci-cd.template.yml
- google/install-chrome/mint-leaf.yml
While using `google/install-chrome` I ran into a few issues.
First, running `chrome` without `--no-sandbox` was crashing because the `chrome_sandbox` binary did not have the proper permissions and ownership. This PR fixes that.
Second, running `chrome` headed was not working because the task using Chrome did not properly configure a virtual display. This PR adds some docs around using `xvfb-run` to use Chrome in that manner.
> Ensure Chrome can be used headed and headless

- .mint/build-tasks.mjs
- .mint/ci.yml
- rwx/install-abq/README.md
- rwx/install-abq/mint-ci-cd.template.yml
- rwx/install-abq/mint-leaf.yml
Now that we have the default RWX_ACCESS_TOKEN in the environment, we can make this optional.
> [rwx/install-abq] Make RWX_ACCESS_TOKEN optional

- azure/install-cli/README.md
- azure/install-cli/mint-ci-cd.template.yml
- azure/install-cli/mint-leaf.yml
Follows the instructions in https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-2-step-by-step-installation-instructions to install the Azure CLI.
Not all versions are available via apt. I suspect it's mostly due to how long the ubuntu release has been around since it's pinned to the dist (we have versions going back to ~2022)
This error is provided when you pass an unsupported version: ![CleanShot 2024-10-17 at 11 41 45@2x](https://github.com/user-attachments/assets/cde9e66e-16b5-420d-95d8-804cb107853a)
> Add a leaf to install the azure CLI

- aws/assume-role/README.md
- aws/assume-role/mint-leaf.yml
- mint/update-leaves-github/README.md
- mint/update-leaves-github/mint-ci-cd.template.yml
- mint/update-leaves-github/mint-leaf.yml
- rwx/install-abq/README.md
- rwx/install-abq/mint-leaf.yml
We're deprecating `mint.run` in favor of `run`
> Use run.id instead of mint.run.id

- mint/git-clone/README.md
- mint/git-clone/mint-ci-cd.template.yml
- mint/git-clone/mint-leaf.yml
Previously, we were pulling in LFS files as part of the same task that cloned the repo. This has some unideal characteristics -- LFS files may change very infrequently, and bandwidth costs for pulling LFS files can be really high, plus it can be somewhat slow to pull them in. By pulling them in an independent filtered task, we can cache the files in a Mint layer so long as they don't change.
The general strategy here is to use `git-lfs ls-files` to find all the LFS files in the repo, and then manually download each file into the appropriate location in a task that is filtered to just the LFS files.
> Cache LFS files separately when cloning

- mint/git-clone/README.md
- mint/git-clone/mint-leaf.yml
This wasn't working when you had multiple LFS files because we were interpolating the LFS files list directly into the dynamic task -- now we pass it through a value which fixes the syntax issue.
> Fixes cloning multiple LFS files

- mint/git-clone/README.md
- mint/git-clone/bin/git-clone
- mint/git-clone/mint-leaf.yml
This uses shallow cloning when you aren't preserving the git directory. Typically shallow cloning is dangerous because a whole host of git operations get messed up, but since we're going to throw the git directory away anyway, we don't need to worry about that.
I also moved the clone script out to a dedicated file. It was getting really difficult to work on directly inside the Mint task.
> Use shallow cloning

- mint/git-clone/README.md
- mint/git-clone/bin/git-clone
- mint/git-clone/mint-ci-cd.template.yml
- mint/git-clone/mint-leaf.yml
Typically, a shallow clone is better when you are not preserving the git dir because there is significantly less data to download. We've seen some cases where a full depth fetch performs significantly better, however. In one case a multi-gigabyte repository took ~3 minutes to fetch with a shallow fetch and half the time to fetch full depth.
> [mint/git-clone] Adds an option to clone with a full depth fetch

- google/install-chrome/README.md
- google/install-chrome/mint-ci-cd.template.yml
- google/install-chrome/mint-leaf.yml
Tools like Karma and TestCafe expect a binary named `google-chrome` in the `PATH`
> Add an alias for google-chrome

- mint/install-node/README.md
- mint/install-node/bin/install-node
- mint/install-node/mint-ci-cd.template.yml
- mint/install-node/mint-leaf.yml
This moves the installation directory for Node from the leaf directory to `/opt/node/v${version}`
Tested new leaf on Mint via [this run](https://cloud.rwx.com/mint/rwx/runs/45a78823b6bf4ce9b7e99190f9792891)
> [mint/install-node] Change installation directory

- mint/git-clone/README.md
- mint/git-clone/bin/git-clone
- mint/git-clone/mint-leaf.yml
This will allow clones to be cache hits when large runs embed many other runs that do the same clones.
> [mint/git-clone] Exclude the github token from the cache key

- cspell.yaml
- twingate/setup/README.md
- twingate/setup/mint-ci-cd.template.yml
- twingate/setup/mint-leaf.yml
Example usage:
```
tasks:
- key: twingate
call: twingate/setup 1.0.0
with:
twingate-service-key: ${{ secrets.twingate-service-key }}
- key: test
use: twingate
background-processes:                                                                            
- key: twingate                                                                                
run: sudo twingate start                                                                     
ready-check: twingate status | grep online 
run: |
// do stuff here
```
> Add twingate/setup leaf

- mint/install-ruby/README.md
- mint/install-ruby/mint-ci-cd.template.yml
- mint/install-ruby/mint-leaf.yml
Bundler is more lenient than their docs would imply: https://github.com/rubygems/rubygems/blob/74f171a05cd02f14b7f0c00b3996089629480186/bundler/lib/bundler/ruby_dsl.rb#L30-L42
> Handle a ruby- prefix in .ruby-version

- aws/assume-role/README.md
- aws/assume-role/mint-leaf.yml
Emit deprecation warning informing users of the incoming changes to aws/assume-role in #188 
Blocked by task emitted mint warnings rolling out to daily mint release.
> Emit warning of aws/assume-role deprecation

- mint/git-clone/README.md
- mint/git-clone/bin/git-clone
- mint/git-clone/mint-ci-cd.template.yml
- mint/git-clone/mint-leaf.yml
By default, git submodules are now pulled during a git clone. This can be disabled with `submodules: false`.
The tests using SSH key auth disable git submodules because the submodule was added via a `https:` URL.
> [mint/git-clone] Pull git submodules after initial clone.

- .mint/build-tasks.mjs
- google/install-chrome/README.md
- google/install-chrome/mint-ci-cd.template.yml
- google/install-chrome/mint-leaf.yml
- mint/install-cli/README.md
- mint/install-cli/mint-ci-cd.config.yml
- mint/install-cli/mint-leaf.yml
- mint/install-erlang/README.md
- mint/install-erlang/mint-ci-cd.config.yml
- mint/install-erlang/mint-ci-cd.template.yml
- mint/install-erlang/mint-ci-cd.ubuntu-22-04.yml
- mint/install-erlang/mint-ci-cd.ubuntu-24-04.yml
- mint/install-erlang/mint-leaf.yml
Allow leaves to run against different base permutations by adding a `mint-ci-cd.config.yml` to the leaf directory.
In some cases, we want to run the same tests against multiple base targets. In this case, put the tasks array into a file (here, `mint-ci-cd.template.yml`) and create `mint-ci-cd.config.yml`:
```yaml
tests:
- key: ubuntu-22-04-x86-64-1-0
template: mint-ci-cd.template.yml
base:
os: ubuntu 22.04
tag: 1.0
arch: x86_64
- key: ubuntu-24-04-x86-64-1-0
template: mint-ci-cd.template.yml
base:
os: ubuntu 24.04
tag: 1.0
arch: x86_64
```
In other cases, we want to run **different** tests against different base targets. Put the tasks array into different yaml files (here, `mint-ci-cd.ubuntu-22-04.yml` and `mint-ci-cd.ubuntu-24-04.yml`) and create `mint-ci-cd.config.yml`:
```yaml
tests:
- …
```
> Configure leaves to run against base permutations.

- mint-utils.sh
- mint/install-erlang/README.md
- mint/install-erlang/mint-leaf.yml
- mint/install-erlang/mint-utils.sh
- render/deploy/README.md
- render/deploy/mint-leaf.yml
Add a script that can be used in a leaf to detect things like OS name, OS version, and version comparisons (`>=`, `<=`).
After discussing a few ways to share this script, Dan and I settled on manually copying it to leaves that use it. That way, they still become part of the leaf test/release cycle (unlike mounting them from an agent), and we aren't forced to do a version bump on every leaf at the same time.
I've included a version comment in the file so we can script a way to identify which leaves may want an update if a bug is detected in the helper script.
> Include `mint-utils.sh` helper functions with leaves.

- mint/install-cli/README.md
- mint/install-cli/mint-ci-cd.template.yml
- mint/install-cli/mint-leaf.yml
- rwx/install-abq/README.md
- rwx/install-abq/mint-ci-cd.template.yml
- rwx/install-abq/mint-leaf.yml
- rwx/install-captain/README.md
- rwx/install-captain/mint-leaf.yml
Currently, the ABQ leaf downloads a binary for every run. This fixes that and uses the new cache TTL feature for Captain and Mint CLIs
https://www.rwx.com/docs/mint/caching#setting-ttls
> Add cache ttls for abq and captain

- azure/install-cli/README.md
- azure/install-cli/mint-ci-cd.config.yml
- azure/install-cli/mint-leaf.yml
- github/install-cli/README.md
- github/install-cli/mint-ci-cd.config.yml
- github/install-cli/mint-leaf.yml
- hashicorp/install-terraform/README.md
- hashicorp/install-terraform/mint-ci-cd.config.yml
- hashicorp/install-terraform/mint-leaf.yml
- mint/git-clone/README.md
- mint/git-clone/mint-ci-cd.config.yml
- mint/git-clone/mint-leaf.yml
- mint/install-go/README.md
- mint/install-go/mint-ci-cd.config.yml
- mint/install-go/mint-leaf.yml
- mint/install-node/README.md
- mint/install-node/mint-ci-cd.config.yml
- mint/install-node/mint-leaf.yml
- rwx/install-abq/README.md
- rwx/install-abq/mint-ci-cd.config.yml
- rwx/install-abq/mint-leaf.yml
- rwx/install-captain/README.md
- rwx/install-captain/mint-ci-cd.config.yml
- rwx/install-captain/mint-leaf.yml
- twingate/setup/README.md
- twingate/setup/mint-ci-cd.config.yml
- twingate/setup/mint-leaf.yml
This runs tests against both Ubuntu 22 and 24 for leaves that may depend on certain versions of apt packages, etc.
The remaining leaf not addressed here is `google/install-chrome` which needs changes and will be updated separately.
> Test more leaves against Ubuntu 24.

- google/install-chrome/README.md
- google/install-chrome/mint-ci-cd.config.yml
- google/install-chrome/mint-ci-cd.template.yml
- google/install-chrome/mint-leaf.yml
- google/install-chrome/mint-utils.sh
Package dependencies were taken from the current Chrome `.deb` and cut down a bit (since we're using `xvfb` and only a few X11 tools, not a full X11 server).
> [google/install-chrome] Add support for Ubuntu 24.04; release v2.1.0

- aws/assume-role/README.md
- aws/assume-role/mint-leaf.yml
There's no need for this to be cache: false.
> Removes cache: false from aws/assume-role
