rwx-research/mint-leaves

per-leaf-tasks.template.yml

To help make the files more deterministic.

Pass the --no-extra flag when zipping

---

.mint/ci.yml

`mint leaves update $(find .mint -type f)` with https://github.com/rwx-research/mint-cli/pull/46

Bump mint-leaves

---

.mint/ci.yml
install-captain/README.md
install-captain/mint-ci-cd.template.yml
install-captain/mint-leaf.yml
per-leaf-tasks.template.yml
publish-tasks.template.yml

Adds an `rwx/install-captain` leaf to install https://github.com/rwx-research/captain
https://cloud.rwx.com/leaves/970e62ac0a3d61f6ffc32b988d0b6a74d2ce77c8968b935deb6c958f72ef0264

Add a leaf for installing Captain

---

install-abq/README.md
install-abq/mint-ci-cd.template.yml
install-abq/mint-leaf.yml

https://cloud.rwx.com/leaves/ec41e67b8e0d2ec41c77556bcbf7dab6ccd3875c8cf1926af62df346f61d9f70

Add a leaf to install ABQ

---

aws/install-cli/README.md
aws/install-cli/mint-ci-cd.template.yml
aws/install-cli/mint-leaf.yml

Introduces a new leaf which handles installing the AWS CLI. Another PR will introduce a leaf that assumes a role

Install the AWS CLI

---

aws/assume-role/README.md
aws/assume-role/mint-ci-cd.template.yml
aws/assume-role/mint-leaf.yml
cspell.yaml

Adds a leaf which assumes a role given an OIDC token

v1 of aws/assume-role

---

google-cloud/auth-credentials/README.md
google-cloud/auth-credentials/mint-ci-cd.template.yml
google-cloud/auth-credentials/mint-leaf.yml
google-cloud/auth-oidc/README.md
google-cloud/auth-oidc/mint-ci-cd.template.yml
google-cloud/auth-oidc/mint-leaf.yml

Add support for both OIDC and [service account credentials JSON](https://developers.google.com/workspace/guides/create-credentials#service-account).

Add google-cloud/auth-oidc and auth-credentials leaves.

---

mint/git-clone/README.md
mint/git-clone/mint-leaf.yml

We need to add support for expressions under `cache` to support this.

Allow git-clone to cache given a specific commit

---

mint/git-clone/README.md
mint/git-clone/mint-ci-cd.template.yml
mint/git-clone/mint-leaf.yml

See the title of this PR and the inline comments

Update git-clone to configure git user and email, and cache better

---

.mint/update-leaves.yml

Manually ran here: https://github.com/rwx-research/mint-leaves/pull/78

Enable auto-update mint leaves.

---

mint/git-clone/README.md
mint/git-clone/mint-leaf.yml

I missed two cache: false

---

.mint/ci.yml
mint/update-leaves-github/README.md
mint/update-leaves-github/mint-ci-cd.template.yml
mint/update-leaves-github/mint-leaf.yml

Use the new git-clone, update update-leaves-github

---

mint/update-leaves-github/README.md
mint/update-leaves-github/mint-leaf.yml

Looks good in testing:
https://github.com/rwx-research/mint-update-leaves-testing/pull/72

Update format when opening PRs to update leaves

---

.mint/build-tasks.mjs
.mint/ci.yml

Tested in https://github.com/rwx-research/mint-leaves/pull/121

Implement build avoidance

---

mint/install-node/README.md
mint/install-node/bin/install-node
mint/install-node/mint-ci-cd.template.yml
mint/install-node/mint-leaf.yml

Example of encountering this error:
https://cloud.rwx.com/mint/rwx/tasks/f4b1f1b59a1c7dee3c6813a7e80c056f/tasks

Friendly error when failing to verify Node GPG sig

---

google/install-chrome/README.md
google/install-chrome/mint-ci-cd.template.yml
google/install-chrome/mint-leaf.yml

It looks like we were hitting a race condition and needed to wait for `driver.title` to return.

Fix google chrome tests

---

azure/auth-oidc/README.md
azure/auth-oidc/mint-ci-cd.template.yml
azure/auth-oidc/mint-leaf.yml

Provides a leaf to authenticate with Azure via OIDC

Auth with azure via OIDC

---

.mint/build-tasks.mjs
package-lock.json
package.json

Taking over https://github.com/rwx-research/mint-leaves/pull/162, this is making space to build a Go binary

Add support for a build script within a leaf

---

.mint/build-tasks.mjs

Pulling these out of https://github.com/rwx-research/mint-leaves/pull/162 so I can avoid running every leaf's build 😅

Upstream some build fixes

---

cspell.yaml
google/install-chrome/README.md
google/install-chrome/mint-leaf.yml
kubernetes/install-cli/README.md
kubernetes/install-cli/mint-ci-cd.template.yml
kubernetes/install-cli/mint-leaf.yml
sonarsource/install-sonar-scanner/README.md
sonarsource/install-sonar-scanner/mint-ci-cd.template.yml
sonarsource/install-sonar-scanner/mint-leaf.yml

- **Fix broken source code urls**
- **Add sonarsource/install-sonar-scanner**

Add sonarsource/install-sonar-scanner

---

mint/install-go/README.md
mint/install-go/bin/clean-system-repository
mint/install-go/bin/install-go
mint/install-go/bin/update-system-repository
mint/install-go/mint-ci-cd.template.yml
mint/install-go/mint-leaf.yml

I moved the install dir out of the leaf dir and into `/opt/go`. I also reduced the tasks from 4 to 1.

Change Go install dir and reduce tasks

---

cspell.yaml
rust-lang/install/README.md
rust-lang/install/mint-ci-cd.template.yml
rust-lang/install/mint-leaf.yml

I've been wanting this for a while 😅 finally got around to it

Add a leaf to install Rust

---

aws/assume-role/README.md
aws/assume-role/mint-ci-cd.template.yml
aws/assume-role/mint-leaf.yml
google-cloud/auth-credentials/README.md
google-cloud/auth-credentials/mint-ci-cd.template.yml
google-cloud/auth-credentials/mint-leaf.yml
google-cloud/auth-oidc/README.md
google-cloud/auth-oidc/mint-ci-cd.template.yml
google-cloud/auth-oidc/mint-leaf.yml
google-cloud/install-cli/README.md
google-cloud/install-cli/mint-leaf.yml
google/install-chrome/README.md
google/install-chrome/mint-ci-cd.template.yml
google/install-chrome/mint-leaf.yml
mint/install-elixir/README.md
mint/install-elixir/mint-leaf.yml
mint/tool-versions/README.md
mint/tool-versions/mint-leaf.yml
mint/update-leaves-github/README.md
mint/update-leaves-github/mint-ci-cd.template.yml
mint/update-leaves-github/mint-leaf.yml

I ran:
```
mint leaves update */*/mint-leaf.yml --allow-major-version-change
mint leaves update */*/mint-ci-cd.template.yml --allow-major-version-change
mint leaves update */*/README.md --allow-major-version-change
```
then bumped up the versions of any affected leaves.

Update all the leaf references within leaves

---

render/deploy/README.md
render/deploy/mint-ci-cd.template.yml
render/deploy/mint-leaf.yml

Initial support for deploying to Render using their API.
This leaf includes two test deployments to Render:

[render/deploy] Initial v1.0.0

---

aws/install-cli/README.md
aws/install-cli/mint-ci-cd.template.yml
aws/install-cli/mint-leaf.yml

I grabbed this new key from https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

Import the new aws cli signing key

---

azure/install-cli/README.md
azure/install-cli/mint-leaf.yml
github/install-cli/README.md
github/install-cli/mint-leaf.yml
google-cloud/install-cli/README.md
google-cloud/install-cli/mint-leaf.yml
google/install-chrome/README.md
google/install-chrome/mint-leaf.yml
hashicorp/install-terraform/README.md
hashicorp/install-terraform/mint-leaf.yml
mint/git-clone/README.md
mint/git-clone/mint-leaf.yml
mint/install-erlang/README.md
mint/install-erlang/mint-leaf.yml
mint/install-node/README.md
mint/install-node/mint-leaf.yml
twingate/setup/README.md
twingate/setup/mint-leaf.yml

Try to reduce the number of tasks used in leaves to reduce overall overhead.

Combine check-os with install task.

---

mint/install-elixir/README.md
mint/install-elixir/mint-ci-cd.template.yml
mint/install-elixir/mint-leaf.yml
mint/install-erlang/README.md
mint/install-erlang/mint-leaf.yml
mint/install-node/README.md
mint/install-node/mint-leaf.yml
rust-lang/install/README.md
rust-lang/install/mint-leaf.yml

I'll follow this up with something that verifies these URLs all work in CI.

Fixes broken source_code_urls

---

google/install-chrome/README.md
google/install-chrome/mint-ci-cd.template.yml
google/install-chrome/mint-leaf.yml

Internal context: https://rwxhq.slack.com/archives/C044VB13K6G/p1749042630621039

Pin the Chrome version used for testing
